export type AiProviderCostTier = "free" | "paid" | "paid_or_unknown";

export type AiProviderCallKind =
  | "chat_completion"
  | "text_generation"
  | "embedding"
  | "image_generation"
  | "video_generation"
  | "transcription"
  | "speech_generation"
  | "classification"
  | "reranking"
  | "prediction"
  | "model_listing";

export interface AiProviderInventoryEntry {
  id: string;
  provider: string;
  surface: string;
  call_kind: AiProviderCallKind;
  model: string;
  cost_tier: AiProviderCostTier;
  default_allowed: boolean;
  allow_paid_flag?: string;
  notes: string;
}

export interface AiProviderDecisionInput {
  path_id: string;
  model?: string | null;
  allow_paid?: boolean;
}

export interface AiProviderCallDecision {
  allowed: boolean;
  path_id: string;
  provider: string;
  model: string;
  cost_tier: AiProviderCostTier;
  default_allowed: boolean;
  reason: "free_default_allowed" | "paid_or_unknown_blocked" | "explicit_paid_allowed";
  allow_paid_flag?: string;
}

export type MemoryAdminAiChatProvider = "google" | "openai" | "anthropic";

const MEMORY_ADMIN_AI_CHAT_PATH_IDS: Record<MemoryAdminAiChatProvider, string> = {
  google: "memory.admin.google.ai-chat",
  openai: "memory.admin.openai.ai-chat",
  anthropic: "memory.admin.anthropic.ai-chat",
};

export const AI_PROVIDER_INVENTORY: AiProviderInventoryEntry[] = [
  {
    id: "nudgeonly.openrouter.free-default",
    provider: "OpenRouter",
    surface: "packages/mcp-server/src/nudgeonly-tool.ts",
    call_kind: "classification",
    model: "liquid/lfm-2.5-1.2b-instruct:free",
    cost_tier: "free",
    default_allowed: true,
    notes: "PinballWake NudgeOnly default route is explicitly labelled free and remains advisory-only.",
  },
  {
    id: "nudgeonly.openrouter.custom-model",
    provider: "OpenRouter",
    surface: "packages/mcp-server/src/nudgeonly-tool.ts",
    call_kind: "classification",
    model: "caller supplied or NUDGEONLY_OPENROUTER_MODEL",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "NUDGEONLY_OPENROUTER_ALLOW_PAID or allow_paid argument",
    notes: "Custom or env-selected NudgeOnly models can be paid or unknown and must require explicit paid opt-in. Free :free routes remain under nudgeonly.openrouter.free-default.",
  },
  {
    id: "event-wake-router.openrouter.classifier",
    provider: "OpenRouter",
    surface: "scripts/event-wake-router.mjs",
    call_kind: "classification",
    model: "OPENROUTER_WAKE_MODEL",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "OPENROUTER_WAKE_ALLOW_PAID",
    notes: "Wake classifier model is environment-selected. Models explicitly ending in :free may run by default; paid or unknown routes must require the wake allow-paid flag.",
  },
  {
    id: "memory.mcp.openai.embeddings",
    provider: "OpenAI",
    surface: "packages/mcp-server/src/memory/embeddings.ts",
    call_kind: "embedding",
    model: "text-embedding-3-small",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "MEMORY_OPENAI_EMBEDDINGS_ENABLED",
    notes: "Memory MCP embeddings already require an explicit true/1 opt-in before calling OpenAI.",
  },
  {
    id: "memory.mcp.openai.fact-extraction",
    provider: "OpenAI",
    surface: "packages/mcp-server/src/memory/supabase.ts",
    call_kind: "chat_completion",
    model: "gpt-4o-mini",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "MEMORY_OPENAI_FACT_EXTRACTION_ENABLED or MEMORY_AI_FACT_EXTRACTION_ENABLED",
    notes: "Memory MCP atomic fact extraction is paid and stays disabled unless a true/1 extraction flag and OPENAI_API_KEY are both present.",
  },
  {
    id: "memory.package.openai.embeddings",
    provider: "OpenAI",
    surface: "packages/memory-mcp/src/embeddings.ts",
    call_kind: "embedding",
    model: "text-embedding-3-small",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "MEMORY_OPENAI_EMBEDDINGS_ENABLED",
    notes: "Standalone Memory MCP embeddings match the explicit true/1 gate and ignore OPENAI_API_KEY alone.",
  },
  {
    id: "memory.api.openai.embed-endpoint",
    provider: "OpenAI",
    surface: "api/memory/embed.ts",
    call_kind: "embedding",
    model: "text-embedding-3-small",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "ADMIN_EMBED_SECRET",
    notes: "Server-only embed endpoint is paid and must stay behind admin secret plus server-side credentials.",
  },
  {
    id: "memory.script.openai.backfill",
    provider: "OpenAI",
    surface: "scripts/backfill-embeddings.ts",
    call_kind: "embedding",
    model: "text-embedding-3-small",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "DRY_RUN=0 with explicit operator launch",
    notes: "Backfill script defaults to a capped operational path, but actual embedding spend is never a free/default path.",
  },
  {
    id: "arena.anthropic.bot-solve",
    provider: "Anthropic",
    surface: "api/arena.ts",
    call_kind: "chat_completion",
    model: "arena_bots.model or claude-haiku-4-5-20251001",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "ARENA_ANTHROPIC_ENABLED",
    notes: "Arena bot solve uses Anthropic for live generated solutions and must require an explicit arena spend opt-in in addition to server-side credentials.",
  },
  {
    id: "memory.admin.google.ai-chat",
    provider: "Google",
    surface: "api/memory-admin.ts?action=admin_ai_chat",
    call_kind: "chat_completion",
    model: "tenant ai_chat_model or gemini-2.5-flash-lite",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "AI_CHAT_ENABLED + tenant ai_chat_enabled + tenant ai_chat_api_key",
    notes: "Memory Admin AI chat can call Google models only after the global chat gate, tenant chat toggle, and tenant-owned API key all pass.",
  },
  {
    id: "memory.admin.openai.ai-chat",
    provider: "OpenAI",
    surface: "api/memory-admin.ts?action=admin_ai_chat",
    call_kind: "chat_completion",
    model: "tenant ai_chat_model or gpt-4o-mini",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "AI_CHAT_ENABLED + tenant ai_chat_enabled + tenant ai_chat_api_key",
    notes: "Memory Admin AI chat can call OpenAI models only after the global chat gate, tenant chat toggle, and tenant-owned API key all pass.",
  },
  {
    id: "memory.admin.anthropic.ai-chat",
    provider: "Anthropic",
    surface: "api/memory-admin.ts?action=admin_ai_chat",
    call_kind: "chat_completion",
    model: "tenant ai_chat_model or claude-haiku-4-5",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "AI_CHAT_ENABLED + tenant ai_chat_enabled + tenant ai_chat_api_key",
    notes: "Memory Admin AI chat can call Anthropic models only after the global chat gate, tenant chat toggle, and tenant-owned API key all pass.",
  },
  {
    id: "mcp.openai.tool.chat",
    provider: "OpenAI",
    surface: "packages/mcp-server/src/openai-tool.ts",
    call_kind: "chat_completion",
    model: "caller supplied or gpt-4o-mini",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP OpenAI tools are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.openai.tool.embedding",
    provider: "OpenAI",
    surface: "packages/mcp-server/src/openai-tool.ts",
    call_kind: "embedding",
    model: "caller supplied or text-embedding-3-small",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP OpenAI embedding calls are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.openai.tool.image-generation",
    provider: "OpenAI",
    surface: "packages/mcp-server/src/openai-tool.ts",
    call_kind: "image_generation",
    model: "caller supplied or dall-e-3",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP OpenAI image generation calls are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.openai.tool.transcription",
    provider: "OpenAI",
    surface: "packages/mcp-server/src/openai-tool.ts",
    call_kind: "transcription",
    model: "caller supplied or whisper-1",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP OpenAI transcription calls are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.openai.tool.model-listing",
    provider: "OpenAI",
    surface: "packages/mcp-server/src/openai-tool.ts",
    call_kind: "model_listing",
    model: "OpenAI /models",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP OpenAI model listing still reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.anthropic.tool.chat",
    provider: "Anthropic",
    surface: "packages/mcp-server/src/anthropic-tool.ts",
    call_kind: "chat_completion",
    model: "caller supplied or claude-sonnet-4-6",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Anthropic tools are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.anthropic.tool.model-listing",
    provider: "Anthropic",
    surface: "packages/mcp-server/src/anthropic-tool.ts",
    call_kind: "model_listing",
    model: "Anthropic /models",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Anthropic model listing still reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.groq.tool.chat",
    provider: "Groq",
    surface: "packages/mcp-server/src/groq-tool.ts",
    call_kind: "chat_completion",
    model: "caller supplied or llama-3.3-70b-versatile",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Groq chat completions are paid or quota-bearing provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.groq.tool.model-listing",
    provider: "Groq",
    surface: "packages/mcp-server/src/groq-tool.ts",
    call_kind: "model_listing",
    model: "Groq /models",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Groq model listing still reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.cohere.tool.chat",
    provider: "Cohere",
    surface: "packages/mcp-server/src/cohere-tool.ts",
    call_kind: "chat_completion",
    model: "caller supplied or command-r-plus",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Cohere chat calls are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.cohere.tool.generate",
    provider: "Cohere",
    surface: "packages/mcp-server/src/cohere-tool.ts",
    call_kind: "text_generation",
    model: "caller supplied or command",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Cohere generate calls are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.cohere.tool.embedding",
    provider: "Cohere",
    surface: "packages/mcp-server/src/cohere-tool.ts",
    call_kind: "embedding",
    model: "caller supplied or embed-english-v3.0",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Cohere embed calls are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.cohere.tool.rerank",
    provider: "Cohere",
    surface: "packages/mcp-server/src/cohere-tool.ts",
    call_kind: "reranking",
    model: "caller supplied or rerank-english-v3.0",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Cohere rerank calls are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.cohere.tool.classify",
    provider: "Cohere",
    surface: "packages/mcp-server/src/cohere-tool.ts",
    call_kind: "classification",
    model: "caller supplied or embed-english-v2.0",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Cohere classify calls are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.cohere.tool.model-listing",
    provider: "Cohere",
    surface: "packages/mcp-server/src/cohere-tool.ts",
    call_kind: "model_listing",
    model: "Cohere /models",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Cohere model listing still reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.togetherai.tool.chat",
    provider: "Together AI",
    surface: "packages/mcp-server/src/togetherai-tool.ts",
    call_kind: "chat_completion",
    model: "caller supplied",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Together AI chat completions are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.togetherai.tool.completion",
    provider: "Together AI",
    surface: "packages/mcp-server/src/togetherai-tool.ts",
    call_kind: "text_generation",
    model: "caller supplied",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Together AI text completions are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.togetherai.tool.embedding",
    provider: "Together AI",
    surface: "packages/mcp-server/src/togetherai-tool.ts",
    call_kind: "embedding",
    model: "caller supplied",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Together AI embeddings are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.togetherai.tool.model-listing",
    provider: "Together AI",
    surface: "packages/mcp-server/src/togetherai-tool.ts",
    call_kind: "model_listing",
    model: "Together AI /models",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Together AI model listing still reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.elevenlabs.tool.text-to-speech",
    provider: "ElevenLabs",
    surface: "packages/mcp-server/src/elevenlabs-tool.ts",
    call_kind: "speech_generation",
    model: "caller supplied or eleven_monolingual_v1",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP ElevenLabs text-to-speech generation is a paid provider call and requires an explicit caller key.",
  },
  {
    id: "mcp.elevenlabs.tool.voice-listing",
    provider: "ElevenLabs",
    surface: "packages/mcp-server/src/elevenlabs-tool.ts",
    call_kind: "model_listing",
    model: "ElevenLabs /voices",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP ElevenLabs voice listing reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.elevenlabs.tool.voice-metadata",
    provider: "ElevenLabs",
    surface: "packages/mcp-server/src/elevenlabs-tool.ts",
    call_kind: "model_listing",
    model: "ElevenLabs /voices/{voice_id}",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP ElevenLabs voice metadata reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.elevenlabs.tool.model-listing",
    provider: "ElevenLabs",
    surface: "packages/mcp-server/src/elevenlabs-tool.ts",
    call_kind: "model_listing",
    model: "ElevenLabs /models",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP ElevenLabs model listing reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.elevenlabs.tool.history",
    provider: "ElevenLabs",
    surface: "packages/mcp-server/src/elevenlabs-tool.ts",
    call_kind: "model_listing",
    model: "ElevenLabs /history",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP ElevenLabs history reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.replicate.tool.prediction",
    provider: "Replicate",
    surface: "packages/mcp-server/src/replicate-tool.ts",
    call_kind: "prediction",
    model: "caller supplied model or version",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_token argument",
    notes: "MCP Replicate prediction creation can run paid models and requires an explicit caller token.",
  },
  {
    id: "mcp.replicate.tool.model-listing",
    provider: "Replicate",
    surface: "packages/mcp-server/src/replicate-tool.ts",
    call_kind: "model_listing",
    model: "Replicate /models",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_token argument",
    notes: "MCP Replicate model listing reaches a provider API and requires an explicit caller token.",
  },
  {
    id: "mcp.replicate.tool.model-metadata",
    provider: "Replicate",
    surface: "packages/mcp-server/src/replicate-tool.ts",
    call_kind: "model_listing",
    model: "Replicate /models/{owner}/{model}",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_token argument",
    notes: "MCP Replicate model metadata reaches a provider API and requires an explicit caller token.",
  },
  {
    id: "mcp.replicate.tool.prediction-status",
    provider: "Replicate",
    surface: "packages/mcp-server/src/replicate-tool.ts",
    call_kind: "prediction",
    model: "existing Replicate prediction",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_token argument",
    notes: "MCP Replicate prediction status can expose paid run state and requires an explicit caller token.",
  },
  {
    id: "mcp.replicate.tool.prediction-listing",
    provider: "Replicate",
    surface: "packages/mcp-server/src/replicate-tool.ts",
    call_kind: "prediction",
    model: "Replicate /predictions",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_token argument",
    notes: "MCP Replicate prediction listing reaches a provider API and requires an explicit caller token.",
  },
  {
    id: "mcp.replicate.tool.prediction-cancel",
    provider: "Replicate",
    surface: "packages/mcp-server/src/replicate-tool.ts",
    call_kind: "prediction",
    model: "existing Replicate prediction",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_token argument",
    notes: "MCP Replicate prediction cancellation mutates provider run state and requires an explicit caller token.",
  },
  {
    id: "mcp.stability.tool.text-to-image",
    provider: "Stability AI",
    surface: "packages/mcp-server/src/stability-tool.ts",
    call_kind: "image_generation",
    model: "caller supplied or stable-diffusion-xl-1024-v1-0",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Stability text-to-image generation is a paid provider call and requires an explicit caller key.",
  },
  {
    id: "mcp.stability.tool.image-to-image",
    provider: "Stability AI",
    surface: "packages/mcp-server/src/stability-tool.ts",
    call_kind: "image_generation",
    model: "caller supplied engine",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Stability image-to-image generation is a paid provider call and requires an explicit caller key.",
  },
  {
    id: "mcp.stability.tool.upscale",
    provider: "Stability AI",
    surface: "packages/mcp-server/src/stability-tool.ts",
    call_kind: "image_generation",
    model: "caller supplied or esrgan-v1-x2plus",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Stability upscaling is a paid provider call and requires an explicit caller key.",
  },
  {
    id: "mcp.stability.tool.engine-listing",
    provider: "Stability AI",
    surface: "packages/mcp-server/src/stability-tool.ts",
    call_kind: "model_listing",
    model: "Stability /engines",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Stability engine listing reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.mistral.tool.chat",
    provider: "Mistral",
    surface: "packages/mcp-server/src/mistral-tool.ts",
    call_kind: "chat_completion",
    model: "caller supplied or mistral-small-latest",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Mistral chat completions are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.mistral.tool.embedding",
    provider: "Mistral",
    surface: "packages/mcp-server/src/mistral-tool.ts",
    call_kind: "embedding",
    model: "caller supplied or mistral-embed",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Mistral embeddings are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.mistral.tool.model-listing",
    provider: "Mistral",
    surface: "packages/mcp-server/src/mistral-tool.ts",
    call_kind: "model_listing",
    model: "Mistral /models",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Mistral model listing reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.perplexity.tool.chat",
    provider: "Perplexity",
    surface: "packages/mcp-server/src/perplexity-tool.ts",
    call_kind: "chat_completion",
    model: "caller supplied or sonar",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Perplexity search-augmented chat completions are paid provider calls and require an explicit caller key.",
  },
  {
    id: "mcp.higgsfield.tool.generate-video",
    provider: "Higgsfield",
    surface: "packages/mcp-server/src/higgsfield-tool.ts",
    call_kind: "video_generation",
    model: "caller supplied prompt and generation options",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Higgsfield video generation is a paid provider call and requires an explicit caller key.",
  },
  {
    id: "mcp.higgsfield.tool.generate-image",
    provider: "Higgsfield",
    surface: "packages/mcp-server/src/higgsfield-tool.ts",
    call_kind: "image_generation",
    model: "caller supplied prompt and generation options",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Higgsfield image generation is a paid provider call and requires an explicit caller key.",
  },
  {
    id: "mcp.higgsfield.tool.style-listing",
    provider: "Higgsfield",
    surface: "packages/mcp-server/src/higgsfield-tool.ts",
    call_kind: "model_listing",
    model: "Higgsfield /styles",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Higgsfield style listing reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.higgsfield.tool.generation-status",
    provider: "Higgsfield",
    surface: "packages/mcp-server/src/higgsfield-tool.ts",
    call_kind: "prediction",
    model: "existing Higgsfield generation",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Higgsfield generation status reaches provider run state and requires an explicit caller key.",
  },
  {
    id: "mcp.heygen.tool.avatar-video",
    provider: "HeyGen",
    surface: "packages/mcp-server/src/heygen-tool.ts",
    call_kind: "video_generation",
    model: "caller supplied avatar and voice inputs",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP HeyGen avatar video generation is a paid provider call and requires an explicit caller key.",
  },
  {
    id: "mcp.heygen.tool.avatar-listing",
    provider: "HeyGen",
    surface: "packages/mcp-server/src/heygen-tool.ts",
    call_kind: "model_listing",
    model: "HeyGen /avatars",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP HeyGen avatar listing reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.heygen.tool.video-status",
    provider: "HeyGen",
    surface: "packages/mcp-server/src/heygen-tool.ts",
    call_kind: "prediction",
    model: "existing HeyGen video",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP HeyGen video status reaches provider run state and requires an explicit caller key.",
  },
  {
    id: "mcp.heygen.tool.voice-listing",
    provider: "HeyGen",
    surface: "packages/mcp-server/src/heygen-tool.ts",
    call_kind: "model_listing",
    model: "HeyGen /voices",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP HeyGen voice listing reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.runway.tool.generate-video",
    provider: "Runway",
    surface: "packages/mcp-server/src/runway-tool.ts",
    call_kind: "video_generation",
    model: "caller supplied or gen3a_turbo",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Runway video generation is a paid provider call and requires an explicit caller key.",
  },
  {
    id: "mcp.runway.tool.generation-status",
    provider: "Runway",
    surface: "packages/mcp-server/src/runway-tool.ts",
    call_kind: "prediction",
    model: "existing Runway task",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Runway task status reaches provider run state and requires an explicit caller key.",
  },
  {
    id: "mcp.runway.tool.model-listing",
    provider: "Runway",
    surface: "packages/mcp-server/src/runway-tool.ts",
    call_kind: "model_listing",
    model: "Runway /models",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Runway model listing reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.pika.tool.generate-video",
    provider: "Pika",
    surface: "packages/mcp-server/src/pika-tool.ts",
    call_kind: "video_generation",
    model: "caller supplied prompt and generation options",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Pika video generation is a paid provider call and requires an explicit caller key.",
  },
  {
    id: "mcp.pika.tool.generation-status",
    provider: "Pika",
    surface: "packages/mcp-server/src/pika-tool.ts",
    call_kind: "prediction",
    model: "existing Pika generation",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Pika generation status reaches provider run state and requires an explicit caller key.",
  },
  {
    id: "mcp.pika.tool.style-listing",
    provider: "Pika",
    surface: "packages/mcp-server/src/pika-tool.ts",
    call_kind: "model_listing",
    model: "Pika /styles",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Pika style listing reaches a provider API and requires an explicit caller key.",
  },
  {
    id: "mcp.kling.tool.generate-video",
    provider: "Kling AI",
    surface: "packages/mcp-server/src/kling-tool.ts",
    call_kind: "video_generation",
    model: "caller supplied or kling-v1",
    cost_tier: "paid",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Kling AI video generation is a paid provider call and requires an explicit caller key.",
  },
  {
    id: "mcp.kling.tool.generation-status",
    provider: "Kling AI",
    surface: "packages/mcp-server/src/kling-tool.ts",
    call_kind: "prediction",
    model: "existing Kling AI task",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "api_key argument",
    notes: "MCP Kling AI task status reaches provider run state and requires an explicit caller key.",
  },
] as const;

export function listAiProviderInventory(): AiProviderInventoryEntry[] {
  return [...AI_PROVIDER_INVENTORY];
}

export function getAiProviderInventoryEntry(pathId: string): AiProviderInventoryEntry | null {
  return AI_PROVIDER_INVENTORY.find((entry) => entry.id === pathId) ?? null;
}

export function getMemoryAdminAiChatPathId(provider: MemoryAdminAiChatProvider): string {
  return MEMORY_ADMIN_AI_CHAT_PATH_IDS[provider];
}

export function classifyAiProviderPath(pathId: string, model?: string | null): AiProviderInventoryEntry {
  const known = getAiProviderInventoryEntry(pathId);
  if (known) {
    return {
      ...known,
      model: model?.trim() || known.model,
    };
  }

  return {
    id: pathId,
    provider: "unknown",
    surface: "unknown",
    call_kind: "chat_completion",
    model: model?.trim() || "unknown",
    cost_tier: "paid_or_unknown",
    default_allowed: false,
    allow_paid_flag: "explicit allow_paid",
    notes: "Unknown provider or model cost must fail closed until inventoried.",
  };
}

export function decideAiProviderCall(input: AiProviderDecisionInput): AiProviderCallDecision {
  const entry = classifyAiProviderPath(input.path_id, input.model);
  const allowPaid = input.allow_paid === true;
  const freeDefault = entry.cost_tier === "free" && entry.default_allowed;

  if (freeDefault) {
    return {
      allowed: true,
      path_id: entry.id,
      provider: entry.provider,
      model: entry.model,
      cost_tier: entry.cost_tier,
      default_allowed: entry.default_allowed,
      reason: "free_default_allowed",
      allow_paid_flag: entry.allow_paid_flag,
    };
  }

  return {
    allowed: allowPaid,
    path_id: entry.id,
    provider: entry.provider,
    model: entry.model,
    cost_tier: entry.cost_tier,
    default_allowed: entry.default_allowed,
    reason: allowPaid ? "explicit_paid_allowed" : "paid_or_unknown_blocked",
    allow_paid_flag: entry.allow_paid_flag,
  };
}

export function decideMemoryAdminAiChatProviderCall(input: {
  provider: MemoryAdminAiChatProvider;
  model?: string | null;
  allow_paid?: boolean;
}): AiProviderCallDecision {
  return decideAiProviderCall({
    path_id: getMemoryAdminAiChatPathId(input.provider),
    model: input.model,
    allow_paid: input.allow_paid,
  });
}

export function publicAiProviderCostLabels(): Array<Pick<
  AiProviderInventoryEntry,
  "id" | "provider" | "surface" | "call_kind" | "model" | "cost_tier" | "default_allowed" | "allow_paid_flag"
>> {
  return AI_PROVIDER_INVENTORY.map((entry) => ({
    id: entry.id,
    provider: entry.provider,
    surface: entry.surface,
    call_kind: entry.call_kind,
    model: entry.model,
    cost_tier: entry.cost_tier,
    default_allowed: entry.default_allowed,
    allow_paid_flag: entry.allow_paid_flag,
  }));
}
