INSERT INTO platform_connectors (id, name, category, auth_type, description, setup_url, test_endpoint, sort_order) VALUES
('neon', 'Neon', 'Dev/Cloud', 'api_key', 'Serverless Postgres with branching - list projects, branches, databases, and execute SQL', 'https://console.neon.tech/app/settings/api-keys', 'https://console.neon.tech/api/v2/projects', 85),
('upstash', 'Upstash', 'Dev/Cloud', 'api_key', 'Serverless Redis and Kafka - read/write keys, produce Kafka messages, list topics', 'https://console.upstash.com/account/api', 'https://api.upstash.com/v2/redis/databases', 86),
('turso', 'Turso', 'Dev/Cloud', 'api_key', 'SQLite edge databases - list databases, create branches, execute SQL at the edge', 'https://turso.tech/app/settings/tokens', 'https://api.turso.tech/v1/organizations', 87),
('render', 'Render', 'Dev/Cloud', 'api_key', 'Cloud hosting - list services, trigger deploys, manage environment variables', 'https://dashboard.render.com/u/settings#api-keys', 'https://api.render.com/v1/services', 88),
('flyio', 'Fly.io', 'Dev/Cloud', 'api_key', 'Global app platform - list apps, inspect machines, launch VMs from Docker images', 'https://fly.io/user/personal_access_tokens', 'https://api.machines.dev/v1/apps', 89),
('mistral', 'Mistral AI', 'AI/ML', 'api_key', 'European frontier AI models - chat completions, embeddings with mistral-small through mistral-large', 'https://console.mistral.ai/api-keys', 'https://api.mistral.ai/v1/models', 90),
('cohere', 'Cohere', 'AI/ML', 'api_key', 'Enterprise NLP platform - chat, embeddings, reranking, and classification with Command R+', 'https://dashboard.cohere.com/api-keys', 'https://api.cohere.com/v1/models', 91),
('perplexity', 'Perplexity AI', 'AI/ML', 'api_key', 'Search-augmented AI - web-grounded answers with citations using Sonar models', 'https://www.perplexity.ai/settings/api', 'https://api.perplexity.ai/chat/completions', 92),
('lemonsqueezy', 'Lemon Squeezy', 'Commerce', 'api_key', 'Digital commerce platform - stores, products, orders, subscriptions, and customers', 'https://app.lemonsqueezy.com/settings/api', 'https://api.lemonsqueezy.com/v1/stores', 93),
('convertkit', 'ConvertKit', 'Creator', 'api_key', 'Creator email platform - subscribers, forms, sequences, and tags for audience automation', 'https://app.convertkit.com/account_settings/advanced_settings', 'https://api.convertkit.com/v3/account', 94);
